### ISSUE TITLE
[FR]Ask an example to create the object detection and tracking tutorial

### ISSUE THREAD

**Issue by twmht** [voxel51/fiftyone-examples#50]
### Instructions

Thank you for submitting an issue. Please refer to our
[issue policy](https://www.github.com/voxel51/fiftyone-examples/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

**Please fill in this template to ensure a timely and thorough response.**

-   Place an "x" between the brackets next to an option if it applies. Example:
    -   [x] Selected option
-   Please delete this section (all content above this line) before submitting
    the issue

### Proposal Summary

(In a few sentences, provide a clear, high-level description of the feature
request)

### Motivation

I found out it was  not easy to read frames from the video when using fiftyone.

I followed the tutorial (https://github.com/voxel51/fiftyone-examples/blob/master/examples/pytorchvideo_tutorial.ipynb), which reads a few video shots and using classification model to classifiy the activities.

But what i want is to use object detection to every frame of the given video, althought the tutorial mentioned the object detection, but is too simple to figure it out.

```
subset.apply_model(model, "detections")
```

Can you give me a simple example to grad each frame from a video sample, and i can use my own model to predict and add labels to the sample?

like, 

```python
sample = fo.Sample(filepath="/path/to/my.mp4")
dataset = fo.Dataset() : type | Unknown
dataset.add_sample(sample)
for frame_number, frame in sample.frames():
    model(frame)
    ....
```

how can i use fiftyone to do that?

### Details

(Use this section to include any additional information about the feature. If
you have a proposal for how to implement this feature, please include it here.)

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [] Yes. I can contribute this feature independently.
-   [] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [x] No. I cannot contribute this feature at this time.
